baseURL = "https://www.ipattern.org"
languageCode = "en-us"
title = "iPattern"
theme = "cactus"
copyright = "iPattern" # cactus will use title if copyright is not set
disqusShortname = "ipattern" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "模式 PATTERN 实验 EXPERIMENT 设计 DESIGN 编程 PRGRAMMING"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "weixin"
    link = "https://mp.weixin.qq.com/s?__biz=Mzg2NTExMzg3Nw==&amp;mid=2247483961&amp;idx=1&amp;sn=bd259184a6498a003e341889314b098f&amp;chksm=ce5e4043f929c9550120ef2145bd0c535286191fd5292895c641d0b4f10d91b3d26f2c6b3ce8&token=300069076&lang=zh_CN#rd"
  [[params.social]]
    name = "youtube"
    link = "https://www.youtube.com/channel/UC4wKXFuLsPV4W8aBkNdb7iA"
  [[params.social]]
    name = "email"
    link = "iPatternPublic@outlook.com"  # no need for "mailto:" in the head
